### ISSUE TITLE
Missing ngram counts

### ISSUE THREAD

**Issue by mfomicheva** [ghpaetzold/questplusplus#16]
Hello Carol. There seems to be a problem with the missing resources generator. I receive a file not found exception when trying to generate missing ngram counts from the corpus data (I double-checked the name of my corpus file and the paths, and everything appears to be correct).

**Comment by carolscarton** [comment]
Hi! I have tried this functionality and everything worked fine here. Could you please send me your config_file?

**Comment by mfomicheva** [comment]
Sorry, Carol. There was a typo in my config file. Everything works fine.
