### ISSUE TITLE
Feature 7001 cannot run

### ISSUE THREAD

**Issue by varvara-l** [ghpaetzold/questplusplus#22]
I've run the sentence-level feature extraction as shown in the README:
java -cp QuEst++.jar shef.mt.SentenceLevelFeatureExtractor -tok -case true -lang english spanish -input input/source.sent-level.en input/target.sent-level.es -config config/config.sentence-level.properties

I get this message:
*********\* Producing output **********
Feature 7001 cannot run because some of its dependencies are missing.
Features will be saved in the following order:
1001    1002    1006    1015    1022    1036    1046    1049    1050    1053    1054    1057    1058    1074    1075

The extractor failed to generate features 1009 and 1012 which are LM log-probabilities for the source and the target. Paths to LMs in the config are valid.

**Comment by varvara-l** [comment]
sorry, the LM features were disabled.
But I'm still getting the same error message, apparently for a reason

**Comment by carolscarton** [comment]
Hi, is the parameter "tools.ngram.path" pointing to the right SRILM folder? This feature 7001 is not part of the baseline features. When did you download QuEst++?

**Comment by varvara-l** [comment]
Apparently I had a bit outdated version of QuEst++, with the newest one it doesn't appear any more.
