### ISSUE TITLE
Stream closed error when running SentenceLevelFeatureExtractor

### ISSUE THREAD

**Issue by antxa** [ghpaetzold/questplusplus#38]
Hi,
I can run without any problem the SentenceLevelFeatureExtractor using the default command in the documentation. But if I change the input files and use the train.source and train.target files from WMT15 (English and Spanish files) instead of source.sent-level.en and target.sent-leves.es files I get this error:

running ./lang_resources/tokenizer/truecase.perl --model ./lang_resources/english/truecase-model.en on [path]/input/test/english/train.source
java.io.IOException: Stream closed
	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
	at java.io.OutputStream.write(OutputStream.java:116)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at shef.mt.tools.Caser.run(Unknown Source)
	at shef.mt.SentenceLevelFeatureExtractor.preProcess(Unknown Source)
	at shef.mt.SentenceLevelFeatureExtractor.run(Unknown Source)
	at shef.mt.SentenceLevelFeatureExtractor.main(Unknown Source)

Any hint?
Thanks!

**Comment by carolscarton** [comment]
Hi, 

I have just tested the recent version of the code and it works when using train.source and train.target.

Can you please check if you have all the required resources and tools? 

Since the problem seems to be on executing the truecase.perl script, could you please try to run it outside QuEst++?

**Comment by antxa** [comment]
I have already test running truecase.perl outside QuEst++ like this (same files):
./lang_resources/tokenizer/truecase.perl --model ./lang_resources/english/truecase-model.en < input/test/english/train.source

And it works...

**Comment by deepakagr-007** [comment]
I too have encountered the same problem. For me this happened when the text contains ® (registered trademark symbol). Any idea how to resolve this?

**Comment by antxa** [comment]
It was an encoding problem in may case. And I resolved the problem changing the locale environment variable like this:
 `setenv LC_ALL en_US.UTF-8`

**Comment by deepakagr-007** [comment]
@antxa :+1: This solved my problem too.

**Comment by fredblain** [comment]
Thanks @antxa for reporting here, what was the reason of your problem.
I close this issue.
