### ISSUE TITLE
How to make .clean file?

### ISSUE THREAD

**Issue by effendijohanes** [ghpaetzold/questplusplus#39]
Hi everyone,

Right now I'm trying to extract sentence and word level quality estimation features.
I saw in the lang_resources folder, the ngram count file with ".clean" extension has header like this (the first 3 lines):

```
0-gram	4	6	14	6703830	
1-gram	3	5	11	1358608	
2-gram	3	5	8	312383	
Monosaccharidzusammensetzung aufweisen ,	15
bis 6 Mikron	3
Heterocyclyl , mit	3
11 ) kommuniziert	3
Nematodenresistenz in	7
```
My question is, how to reproduce the ".clean" file? What program and parameter did you used?
I'm using SRILM ngram-count but only get the ngram count without the header(first three lines).

Thanks for your answer in advance.

**Comment by ghpaetzold** [comment]
Hi Johanes,


To produce this file you will have to use the NGramSorter application that is available within QuEst++.

You can find instructions in the second page of manual below:


https://github.com/ghpaetzold/questplusplus/blob/master/manuals/Sentence-Level%20Quest%2B%2B%20Manual.pdf


Regards,

_______________________________

Gustavo Henrique Paetzold
Research Associate in Text Adaptation
University of Sheffield
________________________________
De: Johanes Effendi <notifications@github.com>
Enviado: quarta-feira, 22 de novembro de 2017 07:55:48
Para: ghpaetzold/questplusplus
Cc: Subscribed
Assunto: [ghpaetzold/questplusplus] How to make .clean file? (#39)


Hi everyone,

Right now I'm trying to extract sentence and word level quality estimation features.
I saw in the lang_resources folder, the ngram count file with ".clean" extension has header like this (the first 3 lines):

0-gram  4       6       14      6703830
1-gram  3       5       11      1358608
2-gram  3       5       8       312383
Monosaccharidzusammensetzung aufweisen ,        15
bis 6 Mikron    3
Heterocyclyl , mit      3
11 ) kommuniziert       3
Nematodenresistenz in   7


My question is, how to reproduce the ".clean" file? What program and parameter did you used?
I'm using SRILM ngram-count but only get the ngram count without the header(first three lines).

Thanks for your answer in advance.

**Comment by effendijohanes** [comment]
Thank you!
