### ISSUE TITLE
Running the tool on english-german data

### ISSUE THREAD

**Issue by murhafh** [ghpaetzold/questplusplus#44]
Hi,

I'm trying to run the tool against a dataset of english-german pairs. Is there a place where I can download the resources needed for german, since the current repo has English, Spanish and Chinese only?

Thanks

**Comment by fredblain** [comment]
Hi @murhafh,
One can either download such resources from the official webpage of the WMT QE shared task (e.g. [2016](http://www.statmt.org/wmt16/quality-estimation-task.html), [2017](http://www.statmt.org/wmt17/quality-estimation-task.html), [2018](http://www.statmt.org/wmt18/quality-estimation-task.html), or create them from the data you consider, using freely available tools (e.g., see [Moses Toolkit](http://www.statmt.org/moses/?n=FactoredTraining.BuildingLanguageModel).
If you're not using data from the WMT tasks, I would rather recommend you to go for the latter solution, i.e. generating your own resources.
Best, Fred.

**Comment by murhafh** [comment]
Thanks @fredblain !
